### ISSUE TITLE
The link to IGS_scripts is down. 

### ISSUE THREAD

**Issue by ltrainstg** [dhimmel/disease-ontology#1]
I was trying to follow along with some of the code examples here to recreate some of the slim files made in this project. 
However, do_tools.py makes reference to IGS_scripts from the IGS/disease-ontology repo, which is no longer up. 
Do you know if these scripts are available anywhere else?

**Comment by dhimmel** [comment]
Thanks for your interest!

> do_tools.py makes reference to IGS_scripts from the IGS/disease-ontology repo

Are you referencing this line:

https://github.com/dhimmel/disease-ontology/blob/052ffcc960f5897a0575f5feff904ca84b7d2c1d/do_tools.py#L3

That line is importing code from the `IGS_scripts` [directory](https://github.com/dhimmel/disease-ontology/tree/gh-pages/IGS_scripts) in this repository. It looks like I copied over all of the IGS scripts to this repo. So these scripts should be available without an external dependency.

If you're looking for the original `IGS/disease-ontology` repo, it looks like there are a couple forks still around like https://github.com/cerdman/disease-ontology. Not sure why @IGS deleted this repo instead of archiving it.

**Comment by ltrainstg** [comment]
Thanks for getting to this so fast. 
I was talking about the link in the README.md on the main page for the repo. 
I didn't see the directory thanks for pointing it out! 
I think I just searched 'IGS_scripts' in the repo and only saw the link and the reference in the file and panicked. 
I should be good now thanks.
